language: python
python:
  - "3.5"
  - "3.6"
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
install: pip install codecov
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
script: python setup.py test
branches:
  only:
    - master
after_success:
  - codecov
